### ISSUE TITLE
模版消息发送失败

### ISSUE THREAD

**Issue by webclz** [callmez/yii2-wechat-sdk#20]
$arr = array(
          'first'=>'first',
          'Topic'=>'topic',
          'Time'=>date('Y-m-d H:i:s',time()),
          'Address'=>'Address',
          'remark'=>'remark'
        );

       $wechat = Yii::$app->wechat;
        // 发送模版消息
       $result = $wechat->sendTemplateMessage('openid','模版id',$arr);
       var_dump($result);

这样来配置，发送消息失败，不知道是什么原因

**Comment by callmez** [comment]
`Yii::$app->wechat->lastError;`可以看到错误信息
