### ISSUE TITLE
微信EncodingAESKey 在您这怎么没有体现出来？

### ISSUE THREAD

**Issue by yccphp** [callmez/yii2-wechat-sdk#3]
微信的 EncodingAESKey 功能，好像在您这没有

**Comment by zacksleo** [comment]
如果是Yii1，需要修改那些地方？

**Comment by qw150986416** [comment]
Yii1 去掉命名空间用到的那些类 继承CComponent

**Comment by callmez** [comment]
加密功能完成

**Comment by callmez** [comment]
related https://github.com/callmez/yii2-wechat-sdk/commit/8088343dbf04f6bd5ae3be04a5d43e3e385806c3
