### ISSUE TITLE
你这个变量没定义itemTag

### ISSUE THREAD

**Issue by magic007** [callmez/yii2-wechat-sdk#36]
Getting unknown property: callmez\wechat\components\MpWechat::itemTag

**Comment by callmez** [comment]
能给个代码重现么?

**Comment by magic007** [comment]
麻烦了，已经解决  你模块里面发送return $this->responseNews($result); 就可以看到。 
`/vendor/callmez/yii2-wechat-sdk/components/BaseWechat.php`
 private $itemTag  里面没这个变量， 你给这个变量定义赋值 item就好。

**Comment by callmez** [comment]
这样应该没有问题吧?

**Comment by magic007** [comment]
恩，这样就可以了。 模块那块功能想的还是挺好的，我已经用上了。 不过由于没文档，费了很大劲

**Comment by callmez** [comment]
谢谢关注!

**Comment by magic007** [comment]
这么厉害，请问现在那座城市工作啊
