### ISSUE TITLE
现在生成二维码时可以支持字符串场景ID了

### ISSUE THREAD

**Issue by bobchengbin** [callmez/yii2-wechat-sdk#7]
http://mp.weixin.qq.com/wiki/18/28fc21e7ed87bec960651f0ce873ef8a.html

**Comment by callmez** [comment]
恩.实现新的参数可能会影响函数的调用调整

**Comment by bobchengbin** [comment]
综合考虑，个人觉得可以写个新的方法。

```php
public function createQrCodeByStr($sceneId, $isLimitScene = false, $expireSeconds = 1800){
// do something
}
```

**Comment by bobchengbin** [comment]
个人感觉这样解决不是很好：
1、理论上来说这个名字最好不要随便换的。。
2、如果非要换方法名或参数，至少有相应的 CHANGELOG  给其它开发者，不然你这就是在埋雷啊。

**Comment by callmez** [comment]
已经发布一个版本号了，版本说明里也提了修改内容，

老版本还是可以用的，你可以通过限定版本号来使用
