### ISSUE TITLE
未定义 WECHAT_TEMPLATE_MESSAGE_SEND_URL 这个常量

### ISSUE THREAD

**Issue by dcb9** [callmez/yii2-wechat-sdk#9]
exception 'yii\base\ErrorException' with message 'Undefined class constant 'WECHAT_TEMPLATE_MESSAGE_SEND_URL'' in /var/www/html/idarex/vendor/callmez/yii2-wechat-sdk/Wechat.php:705

**Comment by callmez** [comment]
感谢!!!
